### ISSUE TITLE
Feature request: browser navigation with pushstate popstate?

### ISSUE THREAD

**Issue by mindfuucker** [proofrock/pupcloud#1]
Pupcloud is a single web-application. So when I hit previous it exits Pupcloud and navigates my browser window to the previous webpage. 
By implementing pushstate and popstate events on path traversal you make the whole application easier to use.

**Comment by proofrock** [comment]
Thanks! It's definitely in the to-do list. I'll look into it as soon as possible, it's annoying me as well 😄

**Comment by proofrock** [comment]
Released in v0.7.2.
