### ISSUE TITLE
Docfix: Multiple profiles 

### ISSUE THREAD

**Issue by vRobM** [proofrock/pupcloud#13]
It took a few minutes to figure out that --share-profile can only accept a single key:value pair, 

But then how does one specify more than one?

Non-obvious:
Turns out with multiple --share-profile parameter invocations in series.

Consider adding comma separated list parsing of key/value pairs with a single parameter invocation.

**Comment by proofrock** [comment]
Thanks for the suggestion. I will detail the feature better in the [docs](https://germ.gitbook.io/pupcloud/guides/running-pupcloud), and sorry for it being a source of confusion.

About allowing a comma separated list: I wanted to do it to address #10, but it would imply that the secrets couldn't contain the comma character, or to introduce some sort of escaping, which I wouldn't like to. It would complicate things. But I think I will just allow it, and if one wants to specify a secret with a comma, they can use the multiple form.

I am creating a new issue to note this last point down. Thanks again.

**Comment by proofrock** [comment]
Done [here](https://germ.gitbook.io/pupcloud/guides/sharing-a-folder#cli-parameters). Let me know if it suffices.

**Comment by proofrock** [comment]
See commit [bf245f4](https://github.com/proofrock/pupcloud/commit/bf245f478dadfd868f888b10efa1b3ffa8b01768)
