### ISSUE TITLE
Sharing only works if shared from localhost

### ISSUE THREAD

**Issue by marioscube** [proofrock/pupcloud#19]
If I start pupcloud with

./pupcloud -r /home/user/Share/pubcloud -E --share-profile John:Secret --share-prefix 'http://192.168.1.140:17179'

If I access pupcloud from
a - localhost
 - <ip>:17178 => I can not "Copy link" copying to clipboard does not work
 - reverse proxy <ip>/pubcloud => I can not "Copy link" copying to clipboard does not work
 - localhost:17178 => I cant "Copy link" copying to clipboard works
b - from any remote computer/IP
 - <ip>:17178 => I can not "Copy link" copying to clipboard does not work
 - reverse proxy <ip>/pubcloud => I can not "Copy link" copying to clipboard does not work
 - obviously I cannot localhost :-)

The link can be opened inside the LAN. (OK)

Is this wanted behavior of pupcloud, a limitation of pupcloud, or do I simply want to much (pupcloud runs on my headless debian server inside a VM. I access pupcloud from my Mac or mobile devices, never from localhost. Or did I misconfigure pupcloud?)

Other point:
the popup on the bottom of the browser screen is there only very short.
 - can it be there longer, or
 - can it be there until the mouse changes shape into a hand?

**Comment by proofrock** [comment]
Interesting. A few questions:

- What do you mean by "_:17178_"? The first and 4th example.
- "_I cant "Copy link" copying to clipboard works_" you mean "I can"? If not, I don't understand if it works or not (3rd example)

Thanks a lot!

**Comment by proofrock** [comment]
_Clipboard feature is available only in secure contexts (HTTPS)_ I overlooked this 😐 I'll rework this part, it's obviously not reliable. I'm still curious of what you mean by "_:17178_"

**Comment by marioscube** [comment]
Something clearly went wrong there ….. formatting?

I wanted t write:
192.168.1.140:17178 on localhost and 192.168.1.140 on other PC clicking the button does not work, does not copy the url to the clipboard.

Only on http:// localhost:17178 it is possible to copy the link to the clipboard.
And as I am never on a browser on localhost I cannot get a share url from the clipboard.

**Comment by proofrock** [comment]
Yes, yes: localhost is a secure context, while any IP in HTTP is not 👎 I'll fix this, and thanks for reporting.

**Comment by proofrock** [comment]
Here [a fix](https://we.tl/t-qDg41X8MfK). Thanks again!

**Comment by marioscube** [comment]
I really like your dirty solution to let the user copy the share url himself.

Maybe it should be made clear in the manual ( I really,really like the manual 👍 ) that the password is **NOT** the secret given in the pupcloud  command line.

Did I say that it works very well? Even from the WAN with ssl.
I might give myself a share to use from outside of my LAN.

Now I wish for a conf file to put all the startup options in.

**Comment by proofrock** [comment]
> Maybe it should be made clear in the manual that the password is NOT the secret given in the pupcloud command line.

Feel free to submit a PR to the v0.8 branch of the [pupcloud-docs](https://github.com/proofrock/pupcloud-docs) project, or just open an issue there with the suggested edit, I'll gladly include it.

> Did I say that it works very well?

That's good to hear, thanks for all the testing!

> Now I wish for a conf file to put all the startup options in.

Open an issue here, I'll do it.

**Comment by marioscube** [comment]
> > Maybe it should be made clear in the manual that the password is NOT the secret given in the pupcloud command line.
> 
> Feel free to submit a PR to the v0.8 branch of the [pupcloud-docs](https://github.com/proofrock/pupcloud-docs) project, or just open an issue there with the suggested edit, I'll gladly include it.

After careful reading of the documentation my suggestion is already covered, maybe not 100% clear on first reading but clear enough. I must ditch my attitude of tl;dr. :-)



> >  Now I wish for a conf file to put all the startup options in.
> 
> Open an issue here, I'll do it.

I'm working on it.

**Comment by proofrock** [comment]
Released in v0.8.0
