### ISSUE TITLE
Sharing user problem

### ISSUE THREAD

**Issue by marioscube** [proofrock/pupcloud#21]
When starting a share I cannot choose the second user. The checkmark is not applied to the second user.
![Screenshot 2022-05-07 at 13 56 52](https://user-images.githubusercontent.com/20281601/167253348-e556fa8b-fefa-45fb-9a00-3f374f499afc.png)

**Comment by proofrock** [comment]
Weird Svelte "bug" (but I'm sure I was misusing something). Fixed. Thanks for reporting.

**Comment by proofrock** [comment]
Released in v0.8.0
