### ISSUE TITLE
Sharing subdirectories, feature or a bug?

### ISSUE THREAD

**Issue by marioscube** [proofrock/pupcloud#24]
If I share when inside a sub-directory (symlinked or not) only that sub-directory is shared. I cannot go UP in the directory tree.

Is this intended behaviour?

I think it's a feature!!! Don't fix.

**Comment by proofrock** [comment]
It's meant to work this way, the "share" button shares the current directory

![immagine](https://user-images.githubusercontent.com/5470600/167256056-ac3784c4-3a40-44f0-89fd-0a002fcdc070.png)

From the docs: "In the Web interface, the sharing URL can be obtained using the "share" button for the current folder."

This all could probably be more explicit/clear 😜

**Comment by marioscube** [comment]
Yeah, like i wrote earlier, I suffer from a mild case of tl;dr.

Great!

**Comment by proofrock** [comment]
It's payback, I am the worst tl;dr-er in the world 😝 I also opened a discussion space here on github (I didn't even know it was possible!), you may be interested. And really, I appreciate what you're doing, feedback is what I need now!
