### ISSUE TITLE
Feature Request: Folder sizes

### ISSUE THREAD

**Issue by garylzimmer** [proofrock/pupcloud#27]
I don't know if this would be possible without creating a database and resource draining process, but I would love to see the sizes of the contents of folders added in their properties. Perhaps just the size of the files in ONLY that folder would be better than any recursion?

**Comment by proofrock** [comment]
Thanks. Also maybe a little less useful? What about putting a small button in the "details" dialog of a folder, and if you press it, it calculates sizes and you just have to wait a little (but you asked for it anyway)? There should also be a way to authorize "heavy" operations on the server (like this or thumbnails), so that people don't DDOS your poor server just by navigationg ;-)

**Comment by garylzimmer** [comment]
Would this manual folder size calculator result be stored? If you only do that operation on demand, you would have to time stamp the result so that anyone reading it would know that it might be outdated.

For the authorization of heavy operations, maybe a power users account group could be made that would be granted such rights?

Or maybe an end user could request such an operation the be authorized by the admin?

**Comment by proofrock** [comment]
On demand, and I have to test it but it shouldn't be too heavy to scan a folder tree and sum the size... but I may be wrong. I don't like to store it, a folder composition could change at any moment, so any kind of timestamping, recent or less, is just telling you "heh, it may be wrong".

I don't also want to introduce the concept of users and groups. It may come to that, but for now I'd like to address a simpler use case.

**Comment by garylzimmer** [comment]
That's understandable. I often have the experience of accessing an unfamiliar file system and wondering where all the media is located. Being able to figure it out by which folder is the largest is often helpful in that regard.

**Comment by proofrock** [comment]
Closing, as this was moved to the roadmap (#43). Thanks!
