### ISSUE TITLE
Share button for when looking at folders and files

### ISSUE THREAD

**Issue by posLop** [proofrock/pupcloud#28]
Right now i can only share a folder that i am currently in.  sometimes i might only want to share a specific file or want to be able to share a folder that is not currently open.  

a share button in the triple bar menu might be a fix.  i did see that multi select is on the way so this prob already planned for after that is done.

great project tho after a few more updates come out ill prob use this full time

**Comment by proofrock** [comment]
Thanks! I want to implement the possibility to share a _file_, not "just" a folder, and if that is done yes... sharing should be in the hamburger menu. I'll keep this open to remind me that I need to work on this, for now thanks a lot! 😜

**Comment by proofrock** [comment]
Closing, as this was moved to the [roadmap](https://github.com/proofrock/pupcloud/wiki/Roadmap!). Thanks!
