### ISSUE TITLE
Default option to hide certain data

### ISSUE THREAD

**Issue by DarrenPIngram** [proofrock/pupcloud#31]
As discussed elsewhere, I really would like the ability for the default to hide the "metadata" such as:

```
Owner: pup (1000)

Group: pup (1000)

Permissions: drwxrwxr-x
```

When viewing a file or directory. I really want to screw down default information.

An external user need not know such info...

**Comment by proofrock** [comment]
I wouldn't put this as the default, in the general case (personal use) it's not very useful. I'm thinking a global option (`--hide-file-details`) that disables it for the "direct" case, a switch in the sharing panel to disable it for the shares, and if the global option is set, it's automatically set also for the shares anyway, along the lines of readonly. What do you think?

**Comment by DarrenPIngram** [comment]
Sure, if you could make it as an environment variable (I think that is the
same as what you mean) I could just add it in the docker-compose.yml (in my
case)

**Comment by proofrock** [comment]
Yes, of course, it will be a commandline switch and an env var. Thanks!

**Comment by proofrock** [comment]
Closing, as this was moved to the [roadmap](https://github.com/proofrock/pupcloud/wiki/Roadmap!). Thanks!
