### ISSUE TITLE
Feature request: logo

### ISSUE THREAD

**Issue by DarrenPIngram** [proofrock/pupcloud#32]
It would be nice if you could consider an optional logo for the login page when a password is set for the share. As an environment variable too that I can refer to in the docker-compose.yml.

As it is now, it just pops up a password box (unless I've missed an existing option).

Just a link would do, e.g. LOGIN_LOGO=/home/user/directory/logo.jpg (or png) No problem with default centering and any size limits (width wise). I am not going to start requesting lots of skinning options!

My launch mode:
```
version: '3.3'
services:
    pupcloud:
        restart: unless-stopped
        container_name: pupcloud
        ports:
            - '8080:17178'
        volumes:
            - '/mnt/disks/D:/data'
        environment:
            - PID=1001
            - PGID=1001
            - PUP_TITLE=xxxxxx
            - PUP_PASSWORD=xxxxxx
        image: 'germanorizzo/pupcloud:latest
```'

**Comment by proofrock** [comment]
It is possible, and it shouldn't be too much work. I'll see what I can do.

**Comment by DarrenPIngram** [comment]
Great, thanks.

**Comment by proofrock** [comment]
Closing, as this was moved to the [roadmap](https://github.com/proofrock/pupcloud/wiki/Roadmap!). Thanks!
