### ISSUE TITLE
Feature request: spinner

### ISSUE THREAD

**Issue by DarrenPIngram** [proofrock/pupcloud#33]
(user-case, data store points to an external network resource, but could also be the same for large local directories).

Could a "spinner" be implemented to show the system has not crashed when navigating to a directory that has not "loaded" (as in it is busy gathering info so "wait").

Happy to give you a private link to test if you wish - you have my email from our exchange a week or so ago re FI/IT).

**Comment by proofrock** [comment]
Hmm, I see! I had performance problems in the past, and in that case it was easier to actually improve pupcloud's performances that implement a spinner 😁 lazy me. This kind of thing always bite you in the... back if you attempt to take shortcuts. Of course, I will do it. I'm not too good at HTML, so it could take a little bit of time.

**Comment by proofrock** [comment]
Closing, as this was moved to the [roadmap](https://github.com/proofrock/pupcloud/wiki/Roadmap!). Thanks!
