### ISSUE TITLE
Lights off

### ISSUE THREAD

**Issue by se7en-x230** [proofrock/pupcloud#35]
Amazing clean, fast and simple project. Love it.

Not the most important but a dark mode would be nice if that's not too much trouble.

**Comment by proofrock** [comment]
Yes, it is in my roadmap. Axentix (the UI toolkit I use) allows for it, but I need to look into it, and it would probably require a sort of reorganization of the toolbar, there are too many icons as it is. But... yes :-) Thanks for stopping by!

**Comment by proofrock** [comment]
Closing, as this was moved to the [roadmap](https://github.com/proofrock/pupcloud/wiki/Roadmap!). Thanks!
