### ISSUE TITLE
Feature request: consideration for multiple accounts

### ISSUE THREAD

**Issue by DarrenPIngram** [proofrock/pupcloud#38]
Would it be possible to consider "multiple accounts" within one (Docker or similar) instance.

E.g. I may have mounted "drive1/" but will keep that not visible.

Then create a share called "dog pics" (data source "drive1/dogpics" and protect it with a password woof. I get a URL to share.
 
Ditto for "cat pics" (data surce "drive1/catpics")

Then "animal pics" (data source "drive1/dogpics" and "drive1/catpics") presently in a sort of union affair.

Result = 3 "public" addresses with an optional password (x3).

Bonus but less critical if individual users can be created and then selecting what directories they can see.
This adds more "filebrowser" behaviour here.

I am aware I could spin up 3 Docker instances, or more, to achieve this in part (not the union, unless I use rclone to join the data sources and then expose the union), but I am presuming this creates greater server load and resource usage. 

Tks

**Comment by proofrock** [comment]
Sorry I'm ina  bit of a hurry now. You can largely do this already:

- navigate to `dog pics`, press the share button, put `woof` as a password. Share this with users set 1.
- navigate to `cat pics`, press the share button, put `meow` as a password. Share this with users set 2.
- navigate back one level (or whatever) to `animal pics`, put `anyoof` as a password. Share this with user set 3.

You have three independent links, with separate passwords and proper isolation. If the folder disappears, the corresponding link becomes invalid and kicks you out.

As an added bonus, they are valid until the pupcloud is launched with the matching profile; if you want to render one invalid, just relaunch pc without that profile (given you assign them to different profiles of course, if not removing the common profile will invalidate them all).

Does this cover your use case?

**Comment by DarrenPIngram** [comment]
I can try 1 and 2 (was not expecting an immediate resolution).

3 may be more difficult, but I can get around it in MY case by making a
separate rclone mount and expose that to a user/permission case.

e.g. join remote:videos/dog/ and remote:pictures/cat to present "animal
picks).

My thoughts were more going towards environment variables in the
config/container.

tks

**Comment by proofrock** [comment]
Aaaaah I'm sorry, I thought that `animal pics/` was parent to both `dog pics` and `cat pics`... I didn't read that you want sort of a union... for now I'd like to stay within the filesystem model, to tell the truth; linux has some provisions for what you need (soft links? bind mounts?) that could satisfy your kind of need...

**Comment by DarrenPIngram** [comment]
NP. For me I can manage it through rclone, but I could see the general utility for users if the config was handled within the app or Docker somehow.


—- 
Via iPad. Hopefully with not too many typos.

**Comment by proofrock** [comment]
Closing, as this was moved to the [roadmap](https://github.com/proofrock/pupcloud/wiki/Roadmap!). Thanks!
