### ISSUE TITLE
Feature request: Environment option for display

### ISSUE THREAD

**Issue by DarrenPIngram** [proofrock/pupcloud#39]
It would be good if such an option could be set to determine whether the default view behaviour is icon view or list view when connecting to a Pupcloud instance (as a user).

**Comment by proofrock** [comment]
Definitely, and a low hanging fruit too. I'll do it. 

(as a side note: I'm pretty busy these days. I'll begin work again in a couple of weeks; I am sorry, it's just to set expectation. In the meanwhile I'll try to consolidate all feature requests in a single discussion, close these issues and make a proper roadmap)

**Comment by marioscube** [comment]
I like this!

Anything that can be set though an env variable is nice.

Managing expectations is always a good thing.

**Comment by DarrenPIngram** [comment]
Yes, certainly we can't demand instant gratification for something we are not paying a penny piece for.
 I will keep giving FR and other feedback as I am giving the application a bit of a constructive "kicking" 

No doubt, as time allows, you prioritise by priority too (show-stoppers, quick fixes or planning larger structural changes). Thank you.

**Comment by proofrock** [comment]
Closing, as this was moved to the [roadmap](https://github.com/proofrock/pupcloud/wiki/Roadmap!). Thanks!
