### ISSUE TITLE
Feature enhancement: file structure cache or pre-fetch

### ISSUE THREAD

**Issue by DarrenPIngram** [proofrock/pupcloud#40]
From my observations and a bit of feedback from test users, there can be some latency issues when retrieving file data from a large exposed instance (in this case c. 45Tb of data).

It seems noticeable as you navigate down a series of directories (with the size/scope growing).

e.g. /root/main title/sub title (27 folders)/possible up to a few hundred or greater folders/up to 10 folders/content

Whether an index (that refreshes itself when a user eventually navigates down in case of change OR something that does an update every hour) or use of the file cache (if possible/used e.g. rclone) is possible I don't know.

User-case, vps mounted Pupcloud, external cloud data store via rclone mounted drive point). It seems empirically slower than comparable Filebrowser configuration so far.

(Some test users felt the thing had crashed, so it puts further desire for the "spinner" on network activity as per the earlier FR).

Edit: this refers ONLY to the file structure metadata and NOT the actual end contents.

[if the developer wants access to the referenced test environment, just contact]

**Comment by proofrock** [comment]
Problem with caches is always the same: how to check that when you get to that subtree, the reality is still aligned with the cache. Basically you have to... re-read everything? I don't know if you can infer it from the directory mod time, to tell the truth. If this is possible, then a `--prefetch` flag that builds a cache is a good idea; if not, well, you could still declare that a folder tree is "stable" and re-launch pup (or press the reload button) to signal that something changed. Interesting. What do you think?

**Comment by proofrock** [comment]
Thanks, I'll check the point I was mentioning earlier and try to structure an idea.

**Comment by proofrock** [comment]
Closing, as this was moved to the [roadmap](https://github.com/proofrock/pupcloud/wiki/Roadmap!). Thanks!

**Comment by proofrock** [comment]
> and a bit of feedback from test users

I cannot PM you so, out of curiosity: who are these users? Please extend my thanks to them!

**Comment by DarrenPIngram** [comment]
You've messaged me on Reddit, but email me (my first name) at (my second
name) dot fi.

Happy to give you some access for stress testing.
