### ISSUE TITLE
Feature request/thought? Webdav

### ISSUE THREAD

**Issue by DarrenPIngram** [proofrock/pupcloud#41]
I don't know how possible it is to add a feature stream, and certainly it should be "opt-in" not to remove the core use of the application.

But if it is easy to somehow add a mini Webdav server (read-only is fine, or whatever permissions otherwise granted to each Pupcloud share) it would be good. An alternative means to get the same files from one point. 

The launch simplicity of Pupcloud is great. So maybe this feature, if possible, may be easiest to implement only in a Docker, if you or another contributor, can add the glue to pull in a webdav server and make the configuration as a slave to Pupcloud being a master.

**Comment by proofrock** [comment]
I would like, at least in this "infancy" phase, to keep things focused (to say it in a posh way, "the unix style" of one tool for one thing ;-). It could be possible, and I see Nextcloud is doing it, but it would be just repackaging a library, I don't think I could re-use much of the backend, or that I could add much value. I'll keep it in the long term roadmap though.

**Comment by DarrenPIngram** [comment]
Thanks. I just come up with the ideas as I find cases and leave it to you
to see if it fits, how it may fit, and if it can be implemented.

**Comment by proofrock** [comment]
I thank you for it. It's what I need.
