### ISSUE TITLE
Feature request: environment for video streaming?

### ISSUE THREAD

**Issue by DarrenPIngram** [proofrock/pupcloud#42]
An environment variable to turn off (optional) ability to stream/watch video from the Pupcloud instance would be nice, e.g. download only and "watch at home".

**Comment by proofrock** [comment]
I can see it would be useful. Not top priority, but it can be done. Thanks!

**Comment by proofrock** [comment]
Closing, as this was moved to the [roadmap](https://github.com/proofrock/pupcloud/wiki/Roadmap!). Thanks!
