### ISSUE TITLE
Sharing with expiring link always "link expired"

### ISSUE THREAD

**Issue by marioscube** [proofrock/pupcloud#46]
This is the first time I test this, so it might be partly my fault for not testing it properly ....... :-)

When I
![Screenshot 2022-05-12 at 19 37 12](https://user-images.githubusercontent.com/20281601/168135983-07c3e8e0-45f8-4080-a9d2-e033d1827d63.png)

Then after input password
![Screenshot 2022-05-12 at 19 37 29](https://user-images.githubusercontent.com/20281601/168136131-27ced49b-85f3-4805-823f-3b5ea5be1b0c.png)

Other dates do not work either.

**Comment by proofrock** [comment]
Oh my! Thanks. I will test it over the weekend.

**Comment by proofrock** [comment]
Fixed in branch `develop`. Thanks!

**Comment by marioscube** [comment]
Thank you.

**Comment by marioscube** [comment]
Can be closed.

**Comment by proofrock** [comment]
Thanks!

**Comment by proofrock** [comment]
No, wait, I'll close it when it will be released ;-) for now the label is enough
