### ISSUE TITLE
No menu in the up right corner

### ISSUE THREAD

**Issue by Nabukodonosor** [proofrock/pupcloud#52]
I've just installed this via docker container, and it works great, but...I don't have these (this is a screenshot from your demo):

https://prnt.sc/XaAGwJy2mdJN

This is how it looks for me:
https://prnt.sc/a9PeUQqgq8Nx

Any ideas?

**Comment by proofrock** [comment]
This is because by default pupcloud launches in read only mode, so the commands that alter a filesystem aren't displayed. Launch it with -E if you want them.

**Comment by Nabukodonosor** [comment]
How to do that? I use Portainer in OMV5.

**Comment by proofrock** [comment]
Don't know with portainer, but you'll want to set an environment variable; in "plain" docker the cli parameter is -e PUP_ALLOW_EDITS=1

Feel free to read the relevant docs over at [dockerhub](https://hub.docker.com/r/germanorizzo/pupcloud).

**Comment by proofrock** [comment]
[This](https://retime.org/portainer-how-to-add-environment-variables-in-a-container/) seems relevant

**Comment by Nabukodonosor** [comment]
Thank you, edited, and now it works. Kinda. :)  Still not share button:
https://prnt.sc/pf-cMke0nKvR

Can I ask you one more question? Is there a way to make image thumbnails, like an image preview instead of the default image icon? Like FileBrowser is doing.

**Comment by proofrock** [comment]
Read the [docs](https://germ.gitbook.io/pupcloud/guides/sharing-a-folder) about sharing, at least a profile is needed, bit you better read it to see how it works. 

About thumbnails: that is on the roadmap, it will be included in a future release. Thanks!

**Comment by Nabukodonosor** [comment]
Awesome. I like it very much, it's very fast, much faster than FileBrowser, but the thumbnail option is a big deal. I hope you make it happen! Cheers!
